### ISSUE TITLE
numpy warnings suppression is not supported

### ISSUE THREAD

**Issue by puddleoasis** [markusressel/py-image-dedup#376]
**Describe the bug**

The project uses `numpy = "1.24.4"`. As of `numpy=1.24.0`, `numpy.warnings` has been removed. When running from the `docker-config.yaml`, the image kept crashing until I commented out `numpy.warnings.filterwarnings('ignore')` in [deduplicator.py](https://github.com/search?q=repo%3Amarkusressel%2Fpy-image-dedup%20numpy.warnings&type=code).

**To Reproduce**
`docker-compose up`. The py_image_dedup crashes for me.
My logs:
```
2024-05-28 20:16:56 Starting daemon...
2024-05-28 20:16:56 DEBUG:py_image_dedup.util:Starting daemon...
2024-05-28 20:16:58 Traceback (most recent call last):
2024-05-28 20:16:58   File "/usr/local/bin/py-image-dedup", line 6, in <module>
2024-05-28 20:16:58     sys.exit(cli())
2024-05-28 20:16:58   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
2024-05-28 20:16:58     return self.main(*args, **kwargs)
2024-05-28 20:16:58   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-05-28 20:16:58     rv = self.invoke(ctx)
2024-05-28 20:16:58   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
2024-05-28 20:16:58     return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-05-28 20:16:58   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
2024-05-28 20:16:58     return ctx.invoke(self.callback, **ctx.params)
2024-05-28 20:16:58   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-05-28 20:16:58     return __callback(*args, **kwargs)
2024-05-28 20:16:58   File "/app/py_image_dedup/cli.py", line 83, in c_daemon
2024-05-28 20:16:58     deduplicator.deduplicate_all()
2024-05-28 20:16:58   File "/app/py_image_dedup/library/deduplicator.py", line 83, in deduplicate_all
2024-05-28 20:16:58     numpy.warnings.filterwarnings('ignore')
2024-05-28 20:16:58   File "/usr/local/lib/python3.10/site-packages/numpy/__init__.py", line 320, in __getattr__
2024-05-28 20:16:58     raise AttributeError("module {!r} has no attribute "
2024-05-28 20:16:58 AttributeError: module 'numpy' has no attribute 'warnings'. Did you mean: 'hanning'?`
```

**Expected behavior**
The container to run.

**Screenshots**

**Desktop (please complete the following information):**
 - OSX, running the Docker Img

**Additional context**

**Comment by markusressel** [comment]
Hi @puddleoasis , thx for the report.
Should be fixed in 9567b10 , please try again with the latest docker image.

**Comment by dassio** [comment]
this still happens using the `docker-compose.yaml` file in the repository

**Comment by markusressel** [comment]
Make sure you are using the latest version. This issue has been fixed a long time ago and there is little reason it should come back.
